# Generated by Django 4.0.6 on 2024-04-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='app/fotos'),
        ),
        migrations.AddField(
            model_name='musica',
            name='link',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
